# New Data Analysis

In [1]:
dataDir='Data/'

In [2]:
import json
import pandas as pd
import numpy as np
import re

## Openning the data¶

In [3]:
#function that open the file and create a "good" dataset
def createDataFrame(file):
    ##lists of 50 data are loaded and then merged
    #create list of dataframes and open file
    dataframes=[]
    file=open(dataDir+file, 'r')
    
    #counter is important for the index
    c=0
    while True:
        #each line is 50 data (as limit=50 when downloading)
        txt=file.readline()
        #possibly stop
        if txt=='':
            break

        #load the data with right index
        j=json.loads(txt)
        l=len(j)
        dataframes.append(pd.DataFrame(j, index=list(range(c, c+l))))
        
        c+=l
    #merge all datasets and return result
    return pd.concat(dataframes)

In [39]:
dfEvent=createDataFrame('event.json')

In [5]:
dfEvent.columns

Index(['beneficiaries_id', 'canceled', 'checks_payable_to_address',
       'contributions_info', 'distribution_paid_for_by', 'end_date',
       'end_time', 'entertainment', 'hosts_id', 'id', 'is_presidential',
       'make_checks_payable_to', 'more_details', 'notes', 'other_members',
       'postponed', 'resource_uri', 'rsvp_info', 'start_date', 'start_time',
       'venue_id'],
      dtype='object')

In [6]:
dfEvent

beneficiaries_id canceled  \
0                [125]    False   
1                [136]    False   
2              [19816]    False   
3          [42, 17513]    False   
4                [125]    False   
5              [18581]    False   
6                [136]    False   
7              [19816]    False   
8              [17256]    False   
9              [18510]    False   
10             [18510]    False   
11             [18499]    False   
12             [18484]    False   
13             [17256]    False   
14               [136]    False   
15               [125]    False   
16             [19748]    False   
17             [18495]    False   
18             [19816]    False   
19               [949]    False   
20               [949]    False   
21             [19748]    False   
22               [699]    False   
23                [42]    False   
24              [1119]    False   
25              [1119]    False   
26                [63]    False   
27             [19748]    False   
28               [125]    False   
29             [18564]    False   
...                ...      ...   
24078            [567]    False   
24079               []    False   
24080               []    False   
24081               []    False   
24082               []    False   
24083               []    False   
24084               []    False   
24085               []    False   
24086               []    False   
24087               []    False   
24088               []    False   
24089               []    False   
24090               []    False   
24091               []    False   
24092               []    False   
24093               []    False   
24094               []    False   
24095               []    False   
24096               []    False   
24097               []    False   
24098               []    False   
24099               []    False   
24100               []    False   
24101               []    False   
24102            [290]    False   
24103               []    False   
24104               []    False   
24105               []    False   
24106               []    False   
24107               []    False   

                               checks_payable_to_address  \
0           617 East Curtis Avenue, Alexandria, VA 22301   
1              217 Third Street SE, Washington, DC 20003   
2                  47 Flintlock Drive, Shirley, NY 11967   
3      Suite 422, 499 South Capitol Street SW, Washin...   
4           617 East Curtis Avenue, Alexandria, VA 22301   
5        4509 Saucon Valley Court, Alexandria, VA, 22312   
6              217 Third Street SE, Washington, DC 20003   
7                  47 Flintlock Drive, Shirley, NY 11967   
8              3410 Alabama Avenue, Alexandria, VA 22305   
9                                                          
10                                                         
11                                                         
12                                                         
13             3410 Alabama Avenue, Alexandria, VA 22305   
14             217 Third Street SE, Washington, DC 20003   
15          617 East Curtis Avenue, Alexandria, VA 22301   
16          4509 Saucon Valley Court Alexandria VA 22312   
17                    PO Box 1295, Gainesville, GA 30503   
18                 47 Flintlock Drive, Shirley, NY 11967   
19                                                         
20                                                         
21          4509 Saucon Valley Court Alexandria VA 22312   
22                     PO Box 341263, Bethesda, MD 20827   
23     415 New Jersey Avenue, SE, Unit 1, Washington,...   
24           417 New Jersey Avenue SE #1, Washington, DC   
25     415 New Jersey Avenue, SE, Unit 1, Washington,...   
26                                                         
27          4509 Saucon Valley Court Alexandria VA 22312   
28          617 East Curtis Avenue, Alexandria, VA 22301   
29                                 

--
### Number of events:

In [7]:
#number of tracked events:
len(dfEvent)

24108

--
### Contributions for each event:

#### looking for host contribution:

see https://regex101.com/r/pj3UC4/1 for more info on the reg expr

In [40]:
def getHostContrib(s):
    reg_expr=re.compile(r'((h|H)ost[ Commitee\:]+\$?[,0-9]+|\$?[,0-9]+[ per\-PACto]+(h|H)ost( [^$]|;|\n|$)|(h|H)ost - \$[,0-9]+)')
    reg_expr2=re.compile(r"[0-9,][0-9,]+")

    if s is None:
        #print(None)
        return None
    else:
        hosts = re.finditer(reg_expr, s)
        c=0
        for hostNum, host in enumerate(hosts):
            c+=1
            a=host.group(0)
        if c==1:
            s=a
        
        n=[]
        nbs = re.finditer(reg_expr2, s)
        for nbNum, nb in enumerate(nbs):
            n.append(int(nb.group(0).replace(',', '')))
        try:
            #print(int(max(n)))
            return max(n)
        except:
            return None
        
        
print(getHostContrib("Host: $2,500 - PAC | $1,500 - Individual / Att..."))
print(getHostContrib("PAC Host | $2,500 - Individual Host /$500 - Individual Guest"))


2500
2500


In [41]:
dfEvent['contributions_info']=dfEvent['contributions_info'].apply(getHostContrib)

In [43]:
dfEvent['contributions_info'].count()

20033

20033 values for contribution over the 24108 events

In [44]:
dfEvent

beneficiaries_id canceled  \
0                [125]    False   
1                [136]    False   
2              [19816]    False   
3          [42, 17513]    False   
4                [125]    False   
5              [18581]    False   
6                [136]    False   
7              [19816]    False   
8              [17256]    False   
9              [18510]    False   
10             [18510]    False   
11             [18499]    False   
12             [18484]    False   
13             [17256]    False   
14               [136]    False   
15               [125]    False   
16             [19748]    False   
17             [18495]    False   
18             [19816]    False   
19               [949]    False   
20               [949]    False   
21             [19748]    False   
22               [699]    False   
23                [42]    False   
24              [1119]    False   
25              [1119]    False   
26                [63]    False   
27             [19748]    False   
28               [125]    False   
29             [18564]    False   
...                ...      ...   
24078            [567]    False   
24079               []    False   
24080               []    False   
24081               []    False   
24082               []    False   
24083               []    False   
24084               []    False   
24085               []    False   
24086               []    False   
24087               []    False   
24088               []    False   
24089               []    False   
24090               []    False   
24091               []    False   
24092               []    False   
24093               []    False   
24094               []    False   
24095               []    False   
24096               []    False   
24097               []    False   
24098               []    False   
24099               []    False   
24100               []    False   
24101               []    False   
24102            [290]    False   
24103               []    False   
24104               []    False   
24105               []    False   
24106               []    False   
24107               []    False   

                               checks_payable_to_address  contributions_info  \
0           617 East Curtis Avenue, Alexandria, VA 22301                 NaN   
1              217 Third Street SE, Washington, DC 20003                 NaN   
2                  47 Flintlock Drive, Shirley, NY 11967                 NaN   
3      Suite 422, 499 South Capitol Street SW, Washin...                 NaN   
4           617 East Curtis Avenue, Alexandria, VA 22301                 NaN   
5        4509 Saucon Valley Court, Alexandria, VA, 22312                 NaN   
6              217 Third Street SE, Washington, DC 20003                 NaN   
7                  47 Flintlock Drive, Shirley, NY 11967                 NaN   
8              3410 Alabama Avenue, Alexandria, VA 22305                 NaN   
9                                                                        NaN   
10                                                                       NaN   
11                                                                    2500.0   
12                                                                       NaN   
13             3410 Alabama Avenue, Alexandria, VA 22305                 NaN   
14             217 Third Street SE, Washington, DC 20003                 NaN   
15          617 East Curtis Avenue, Alexandria, VA 22301                 NaN   
16          4509 Saucon Valley Court Alexandria VA 22312                 NaN   
17                    PO Box 1295, Gainesville, GA 30503                 NaN   
18                 47 Flintlock Drive, Shirley, NY 11967                 NaN   
19                                                                       NaN   
20                                                                       NaN   
21          4509 Saucon Valley Court Alexandria VA 22312                 Na

NaN is when there is no value found

# Open secret data

In [13]:
dfContrib=createDataFrame("candContrib.json")
dfContrib.columns

Index(['cid', 'indivs', 'org_name', 'pacs', 'total', 'year'], dtype='object')

In [14]:
dfContrib.total=dfContrib.total.apply(int)#.sort_index()#'total')

In [15]:
dfContrib.sort_values(by='total', ascending=False)

cid  indivs                                         org_name  \
380  N00035267  154044                                           NorPAC   
400  N00035267  154044                                           NorPAC   
390  N00035267  154044                                           NorPAC   
401  N00035267  156910                                Paul, Weiss et al   
391  N00035267  154150                                Paul, Weiss Et Al   
381  N00035267  153900                                Paul, Weiss et al   
402  N00035267  100950                                       Gibbons PC   
392  N00035267  100950                                       Gibbons PC   
350  N00000699  106657                           Lowenstein Sandler LLP   
360  N00000699   85550                                           NorPAC   
351  N00000699   85550                                           NorPAC   
352  N00000699   77050                            Greenberg Traurig LLP   
403  N00035267   74210                            Greenberg Traurig LLP   
310  N00000684   83100                               Elliott Management   
404  N00035267   82630                              Sullivan & Cromwell   
393  N00035267   82600                              Sullivan & Cromwell   
382  N00035267   82600                              Sullivan & Cromwell   
80   N00036155   79000                                     Votesane PAC   
394  N00035267   72700                                    Goldman Sachs   
405  N00035267   72700                                    Goldman Sachs   
383  N00035267   72700                                    Goldman Sachs   
406  N00035267   57100                                        DLA Piper   
353  N00000699   66950                             Prudential Financial   
361  N00000699   76897                           Lowenstein Sandler LLP   
395  N00035267   67700                            Greenberg Traurig LLP   
300  N00000684   65700                                  Lockheed Martin   
384  N00035267   69800                                       Gibbons PC   
385  N00035267   54400                                        DLA Piper   
396  N00035267   54400                                        DLA Piper   
290  N00000684   63350                                  Lockheed Martin   
..         ...     ...                                              ...   
118  N00009816       0                                Mid Manhattan PAC   
119  N00009816       0            National Air Traffic Controllers Assn   
116  N00009816       0                                   Laborers Union   
349  N00036158       0                                     Novo Nordisk   
224  N00027523       0                                  Teamsters Union   
282  N00034639       0                       Carpenters & Joiners Union   
283  N00034639       0  International Brotherhood of Electrical Workers   
284  N00034639       0                                Johnson & Johnson   
285  N00034639       0               Machinists/Aerospace Workers Union   
286  N00034639       0                             Prudential Financial   
287  N00034639     500                  Public Service Enterprise Group   
288  N00034639       0           United Food & Commercial Workers Union   
99   N00009816       0                              Covington & Burling   
348  N00036158       0               Machinists/Aerospace Workers Union   
115  N00009816       0                       Carpenters & Joiners Union   
223  N00027523       0               Machinists/Aerospace Workers Union   
222  N00027523       0  International Brotherhood of Electrical Workers   
221  N00027523       0                       Carpenters & Joiners Union   
220  N00027523       0                                         AT&T Inc   
343  N00036158       0                             Bristol-Myers Squibb   
344  N00036158       0                       Carpenters & Joiners Union   
345  N00036158    1000              

In [16]:
grouped=dfContrib['total'].groupby(dfContrib['year'])
grouped

In [17]:
grouped.describe(include='all')

year       
2014  count       130.000000
      mean      23400.784615
      std       27602.586754
      min        5000.000000
      25%       10000.000000
      50%       10999.000000
      75%       20845.250000
      max      158871.000000
2016  count       140.000000
      mean      24105.957143
      std       26270.845031
      min        8000.000000
      25%       10000.000000
      50%       13700.000000
      75%       20843.500000
      max      158871.000000
2018  count       140.000000
      mean      17938.892857
      std       26264.276344
      min        2500.000000
      25%        5400.000000
      50%        9200.000000
      75%       15000.000000
      max      158871.000000
Name: total, dtype: float64